import 'package:shared_preferences/shared_preferences.dart';

class AppLanguage {
  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
  });

  final String code;
  final String name;
  final String nativeName;

  static const english = AppLanguage(
    code: 'en',
    name: 'English',
    nativeName: 'English',
  );
  static const hindi = AppLanguage(
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
  );
  static const telugu = AppLanguage(
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
  );

  static const values = [english, hindi, telugu];

  static AppLanguage byCode(String code) => values.firstWhere(
        (language) => language.code == code,
        orElse: () => english,
      );
}

class LanguageStore {
  static const _key = 'cartsense_language_code_v1';

  Future<AppLanguage> load() async {
    final preferences = await SharedPreferences.getInstance();
    return AppLanguage.byCode(preferences.getString(_key) ?? 'en');
  }

  Future<void> save(AppLanguage language) async {
    final preferences = await SharedPreferences.getInstance();
    await preferences.setString(_key, language.code);
  }
}

String appText(String languageCode, String key) {
  final localized = _translations[languageCode]?[key];
  if (localized != null) return localized;
  return _translations['en']?[key] ?? key;
}

const _translations = {
  'en': {
    'home': 'Home',
    'scan': 'Scan',
    'list': 'List',
    'insights': 'Insights',
    'settings': 'Settings',
    'language': 'Language',
    'chooseLanguage': 'Choose language',
    'languageSubtitle': 'English, Hindi and Telugu support.',
    'languageChanged': 'Language changed',
    'moreOptions': 'More options',
    'smartGroceryCompanion': 'Smart grocery companion',
    'scanGroceryReceipt': 'Scan a grocery receipt',
    'saveProductsPrices': 'Save products, prices and spending automatically.',
    'scanReceipt': 'Scan receipt',
    'longReceiptPhotos': 'Long receipt / multiple photos',
    'chooseAiOrPrivate': 'You choose AI or private on-device scan',
    'yourShortcuts': 'Your shortcuts',
    'budgetPriceTrends': 'Budget and price trends',
    'shoppingAssistant': 'Shopping Assistant',
    'planNextTrip': 'Plan your next trip',
    'productsToBuyCount': 'products to buy',
    'productMaster': 'Product master',
    'usualItemsBestPrices': 'Usual items, favorites and best prices',
    'recentReceipts': 'Recent receipts',
    'noSavedBillsMatch': 'No saved bills match your search.',
    'searchStoresItems': 'Search stores or grocery items',
    'clearSearch': 'Clear search',
    'privateScan': 'Private scan',
    'openSampleReceipt': 'Open sample receipt',
    'scanCheckoutBill': 'Scan your checkout bill',
    'compareWithList':
        'CartSense will compare this bill with your saved shopping list.',
    'aiScanCamera': 'AI scan with camera',
    'aiScanGallery': 'AI scan from gallery',
    'aiScanLong': 'AI scan long / multiple-page bill',
    'captureMultipleSections': 'Capture 2 to 4 top, middle and bottom photos.',
    'privateDeviceScan': 'Private on-device scan',
    'privateReader': 'Private on-device reader',
    'photoStaysPhone': 'The receipt photo stays on this phone.',
    'takePhoto': 'Take a photo',
    'chooseGallery': 'Choose from gallery',
    'estimatedBasket': 'Estimated basket',
    'startTrip': 'Start trip',
    'shareList': 'Share list',
    'smartTripAssistant': 'Smart trip assistant',
    'productsToBuy': 'Products to buy',
    'addProduct': 'Add product',
    'editProduct': 'Edit product',
    'productOrType': 'Product or product type',
    'forExampleTea': 'For example Tea',
    'scanShelfPrice': 'Scan shelf price label',
    'readingShelfPrice': 'Reading shelf price...',
    'shelfPriceCaptured': 'Shelf price captured',
    'quantity': 'Quantity',
    'unitPrice': 'Unit price',
    'category': 'Category',
    'noteOptional': 'Note (optional)',
    'brandSizePreference': 'Brand, size or preference',
    'addReminder': 'Add reminder',
    'cancel': 'Cancel',
    'save': 'Save',
    'saveChanges': 'Save changes',
    'addToList': 'Add to list',
    'tripMode': 'Trip mode',
    'exit': 'Exit',
    'inStoreChecklist': 'In-store checklist',
    'stillToBuy': 'Still to buy',
    'inCart': 'In cart',
    'extraPicked': 'Extra picked in store',
    'checkoutScanBill': 'Checkout done — scan bill',
    'setTripBudget': 'Set trip budget',
    'addExtraItem': 'Add extra item',
    'beforeCounter': 'Before counter',
    'overBudget': 'over budget',
    'insideBudget': 'inside budget',
    'unknownPrices':
        'item prices are unknown. Scan shelf labels or type prices for a better counter estimate.',
    'expectedBillIncludes':
        'Expected bill includes checked planned items plus extras picked during this trip.',
    'removeToReduce': 'To reduce the bill, consider removing:',
    'remove': 'Remove',
    'priceUnknown': 'Price unknown',
    'savesAbout': 'Saves about',
    'backupRestore': 'Backup and restore',
    'appLanguage': 'App language',
    'privacy': 'Privacy',
    'allowAiScan': 'Allow AI Enhanced Scan',
    'allowAiScanSubtitle':
        'When enabled, receipt photos can be sent securely for AI recognition. Private scan remains available.',
    'exportBackup': 'Export backup file',
    'exportBackupSubtitle': 'Save or share a CartSense backup JSON file.',
    'copyBackup': 'Copy backup text',
    'copyBackupSubtitle': 'Useful if a share target is not available.',
    'restoreBackup': 'Restore from backup text',
    'restoreBackupSubtitle': 'Paste a previous CartSense backup.',
    'productMemory': 'Product memory',
    'clearProductMemory': 'Clear product memory',
    'about': 'About',
    'showAppGuide': 'Show app guide',
  },
  'hi': {
    'home': 'होम',
    'scan': 'स्कैन',
    'list': 'सूची',
    'insights': 'जानकारी',
    'settings': 'सेटिंग्स',
    'language': 'भाषा',
    'chooseLanguage': 'भाषा चुनें',
    'languageSubtitle': 'अंग्रेज़ी, हिन्दी और तेलुगु समर्थन.',
    'languageChanged': 'भाषा बदली गई',
    'moreOptions': 'और विकल्प',
    'smartGroceryCompanion': 'स्मार्ट किराना साथी',
    'scanGroceryReceipt': 'किराना बिल स्कैन करें',
    'saveProductsPrices': 'सामान, कीमतें और खर्च अपने आप सेव करें.',
    'scanReceipt': 'बिल स्कैन करें',
    'longReceiptPhotos': 'लंबा बिल / कई फोटो',
    'chooseAiOrPrivate': 'AI या निजी ऑन-डिवाइस स्कैन चुनें',
    'yourShortcuts': 'आपके शॉर्टकट',
    'budgetPriceTrends': 'बजट और कीमत रुझान',
    'shoppingAssistant': 'खरीदारी सहायक',
    'planNextTrip': 'अगली खरीदारी की योजना',
    'productsToBuyCount': 'सामान खरीदने हैं',
    'productMaster': 'प्रोडक्ट मास्टर',
    'usualItemsBestPrices': 'आम सामान, पसंदीदा और अच्छी कीमतें',
    'recentReceipts': 'हाल के बिल',
    'noSavedBillsMatch': 'आपकी खोज से कोई सेव बिल नहीं मिला.',
    'searchStoresItems': 'स्टोर या सामान खोजें',
    'clearSearch': 'खोज साफ करें',
    'privateScan': 'निजी स्कैन',
    'openSampleReceipt': 'नमूना बिल खोलें',
    'scanCheckoutBill': 'चेकआउट बिल स्कैन करें',
    'compareWithList':
        'CartSense इस बिल की तुलना आपकी सेव खरीदारी सूची से करेगा.',
    'aiScanCamera': 'कैमरा से AI स्कैन',
    'aiScanGallery': 'गैलरी से AI स्कैन',
    'aiScanLong': 'लंबे / कई पेज बिल का AI स्कैन',
    'captureMultipleSections': 'ऊपर, बीच और नीचे के 2 से 4 फोटो लें.',
    'privateDeviceScan': 'निजी ऑन-डिवाइस स्कैन',
    'privateReader': 'निजी ऑन-डिवाइस रीडर',
    'photoStaysPhone': 'बिल की फोटो इसी फोन पर रहती है.',
    'takePhoto': 'फोटो लें',
    'chooseGallery': 'गैलरी से चुनें',
    'estimatedBasket': 'अनुमानित बिल',
    'startTrip': 'खरीदारी शुरू करें',
    'shareList': 'सूची शेयर करें',
    'smartTripAssistant': 'स्मार्ट खरीदारी सहायक',
    'productsToBuy': 'खरीदने वाला सामान',
    'addProduct': 'सामान जोड़ें',
    'editProduct': 'सामान बदलें',
    'productOrType': 'सामान या प्रकार',
    'forExampleTea': 'जैसे चाय',
    'scanShelfPrice': 'शेल्फ कीमत स्कैन करें',
    'readingShelfPrice': 'शेल्फ कीमत पढ़ रहे हैं...',
    'shelfPriceCaptured': 'शेल्फ कीमत कैप्चर हुई',
    'quantity': 'मात्रा',
    'unitPrice': 'प्रति यूनिट कीमत',
    'category': 'श्रेणी',
    'noteOptional': 'नोट (वैकल्पिक)',
    'brandSizePreference': 'ब्रांड, साइज या पसंद',
    'addReminder': 'रिमाइंडर जोड़ें',
    'cancel': 'रद्द करें',
    'save': 'सेव',
    'saveChanges': 'बदलाव सेव करें',
    'addToList': 'सूची में जोड़ें',
    'tripMode': 'स्टोर मोड',
    'exit': 'बाहर जाएं',
    'inStoreChecklist': 'स्टोर चेकलिस्ट',
    'stillToBuy': 'अभी खरीदना है',
    'inCart': 'कार्ट में',
    'extraPicked': 'स्टोर में अतिरिक्त लिया',
    'checkoutScanBill': 'बिल हो गया — स्कैन करें',
    'setTripBudget': 'ट्रिप बजट सेट करें',
    'addExtraItem': 'अतिरिक्त सामान जोड़ें',
    'beforeCounter': 'काउंटर से पहले',
    'overBudget': 'बजट से ऊपर',
    'insideBudget': 'बजट में',
    'unknownPrices':
        'सामान की कीमत अज्ञात है. बेहतर अनुमान के लिए शेल्फ लेबल स्कैन करें या कीमत लिखें.',
    'expectedBillIncludes':
        'अनुमानित बिल में चुने हुए सामान और ट्रिप में लिए अतिरिक्त सामान शामिल हैं.',
    'removeToReduce': 'बिल कम करने के लिए हटाने पर विचार करें:',
    'remove': 'हटाएं',
    'priceUnknown': 'कीमत अज्ञात',
    'savesAbout': 'लगभग बचत',
    'backupRestore': 'बैकअप और रिस्टोर',
    'appLanguage': 'ऐप भाषा',
    'privacy': 'प्राइवेसी',
    'allowAiScan': 'AI Enhanced Scan की अनुमति दें',
    'allowAiScanSubtitle':
        'चालू होने पर बिल फोटो सुरक्षित रूप से AI पहचान के लिए भेजी जा सकती है. निजी स्कैन उपलब्ध रहेगा.',
    'exportBackup': 'बैकअप फाइल एक्सपोर्ट करें',
    'exportBackupSubtitle': 'CartSense बैकअप JSON फाइल सेव या शेयर करें.',
    'copyBackup': 'बैकअप टेक्स्ट कॉपी करें',
    'copyBackupSubtitle': 'जब शेयर विकल्प उपलब्ध न हो तो उपयोगी.',
    'restoreBackup': 'बैकअप टेक्स्ट से रिस्टोर करें',
    'restoreBackupSubtitle': 'पुराना CartSense बैकअप पेस्ट करें.',
    'productMemory': 'प्रोडक्ट मेमोरी',
    'clearProductMemory': 'प्रोडक्ट मेमोरी साफ करें',
    'about': 'ऐप के बारे में',
    'showAppGuide': 'ऐप गाइड दिखाएं',
  },
  'te': {
    'home': 'హోమ్',
    'scan': 'స్కాన్',
    'list': 'లిస్ట్',
    'insights': 'ఇన్‌సైట్స్',
    'settings': 'సెట్టింగ్స్',
    'language': 'భాష',
    'chooseLanguage': 'భాష ఎంచుకోండి',
    'languageSubtitle': 'ఇంగ్లీష్, హిందీ మరియు తెలుగు మద్దతు.',
    'languageChanged': 'భాష మార్చబడింది',
    'moreOptions': 'మరిన్ని ఎంపికలు',
    'smartGroceryCompanion': 'స్మార్ట్ గ్రోసరీ సహాయకుడు',
    'scanGroceryReceipt': 'గ్రోసరీ బిల్ స్కాన్ చేయండి',
    'saveProductsPrices':
        'వస్తువులు, ధరలు మరియు ఖర్చు ఆటోమేటిక్‌గా సేవ్ చేయండి.',
    'scanReceipt': 'బిల్ స్కాన్',
    'longReceiptPhotos': 'పొడవైన బిల్ / అనేక ఫోటోలు',
    'chooseAiOrPrivate': 'AI లేదా ప్రైవేట్ ఆన్-డివైస్ స్కాన్ ఎంచుకోండి',
    'yourShortcuts': 'మీ షార్ట్‌కట్లు',
    'budgetPriceTrends': 'బడ్జెట్ మరియు ధరల ట్రెండ్స్',
    'shoppingAssistant': 'షాపింగ్ అసిస్టెంట్',
    'planNextTrip': 'తర్వాతి షాపింగ్ ప్లాన్',
    'productsToBuyCount': 'వస్తువులు కొనాలి',
    'productMaster': 'ప్రోడక్ట్ మాస్టర్',
    'usualItemsBestPrices': 'సాధారణ వస్తువులు, ఇష్టమైనవి మరియు మంచి ధరలు',
    'recentReceipts': 'ఇటీవలి బిల్లులు',
    'noSavedBillsMatch': 'మీ శోధనకు సేవ్ చేసిన బిల్లులు లేవు.',
    'searchStoresItems': 'స్టోర్‌లు లేదా వస్తువులు వెతకండి',
    'clearSearch': 'శోధన క్లియర్',
    'privateScan': 'ప్రైవేట్ స్కాన్',
    'openSampleReceipt': 'నమూనా బిల్ తెరవండి',
    'scanCheckoutBill': 'చెకౌట్ బిల్ స్కాన్ చేయండి',
    'compareWithList':
        'CartSense ఈ బిల్లును మీ సేవ్ చేసిన షాపింగ్ లిస్ట్‌తో పోలుస్తుంది.',
    'aiScanCamera': 'కెమెరాతో AI స్కాన్',
    'aiScanGallery': 'గ్యాలరీ నుండి AI స్కాన్',
    'aiScanLong': 'పొడవైన / అనేక పేజీ బిల్ AI స్కాన్',
    'captureMultipleSections':
        'పై, మధ్య, కింది భాగాల 2 నుండి 4 ఫోటోలు తీసుకోండి.',
    'privateDeviceScan': 'ప్రైవేట్ ఆన్-డివైస్ స్కాన్',
    'privateReader': 'ప్రైవేట్ ఆన్-డివైస్ రీడర్',
    'photoStaysPhone': 'బిల్ ఫోటో ఈ ఫోన్‌లోనే ఉంటుంది.',
    'takePhoto': 'ఫోటో తీయండి',
    'chooseGallery': 'గ్యాలరీ నుండి ఎంచుకోండి',
    'estimatedBasket': 'అంచనా బిల్',
    'startTrip': 'షాపింగ్ మొదలుపెట్టు',
    'shareList': 'లిస్ట్ షేర్',
    'smartTripAssistant': 'స్మార్ట్ షాపింగ్ అసిస్టెంట్',
    'productsToBuy': 'కొనాల్సిన వస్తువులు',
    'addProduct': 'వస్తువు జోడించండి',
    'editProduct': 'వస్తువు మార్చండి',
    'productOrType': 'వస్తువు లేదా రకం',
    'forExampleTea': 'ఉదాహరణకు టీ',
    'scanShelfPrice': 'షెల్ఫ్ ధర స్కాన్ చేయండి',
    'readingShelfPrice': 'షెల్ఫ్ ధర చదువుతోంది...',
    'shelfPriceCaptured': 'షెల్ఫ్ ధర క్యాప్చర్ అయింది',
    'quantity': 'పరిమాణం',
    'unitPrice': 'యూనిట్ ధర',
    'category': 'కేటగిరీ',
    'noteOptional': 'నోట్ (ఐచ్చికం)',
    'brandSizePreference': 'బ్రాండ్, సైజు లేదా అభిరుచి',
    'addReminder': 'రిమైండర్ జోడించండి',
    'cancel': 'రద్దు',
    'save': 'సేవ్',
    'saveChanges': 'మార్పులు సేవ్',
    'addToList': 'లిస్ట్‌లో జోడించండి',
    'tripMode': 'స్టోర్ మోడ్',
    'exit': 'బయటకు',
    'inStoreChecklist': 'స్టోర్ చెక్‌లిస్ట్',
    'stillToBuy': 'ఇంకా కొనాల్సినవి',
    'inCart': 'కార్ట్‌లో',
    'extraPicked': 'స్టోర్‌లో అదనంగా తీసుకున్నవి',
    'checkoutScanBill': 'బిల్ అయింది — స్కాన్ చేయండి',
    'setTripBudget': 'ట్రిప్ బడ్జెట్ సెట్ చేయండి',
    'addExtraItem': 'అదనపు వస్తువు జోడించండి',
    'beforeCounter': 'కౌంటర్ ముందు',
    'overBudget': 'బడ్జెట్ దాటింది',
    'insideBudget': 'బడ్జెట్‌లో ఉంది',
    'unknownPrices':
        'వస్తువుల ధరలు తెలియదు. మంచి అంచనాకు షెల్ఫ్ లేబుల్ స్కాన్ చేయండి లేదా ధర టైప్ చేయండి.',
    'expectedBillIncludes':
        'అంచనా బిల్‌లో చెక్ చేసిన వస్తువులు మరియు ట్రిప్‌లో తీసుకున్న అదనపు వస్తువులు ఉంటాయి.',
    'removeToReduce': 'బిల్ తగ్గించడానికి వీటిని తీసేయండి:',
    'remove': 'తీసేయండి',
    'priceUnknown': 'ధర తెలియదు',
    'savesAbout': 'సుమారు ఆదా',
    'backupRestore': 'బ్యాకప్ మరియు రిస్టోర్',
    'appLanguage': 'యాప్ భాష',
    'privacy': 'ప్రైవసీ',
    'allowAiScan': 'AI Enhanced Scan అనుమతించండి',
    'allowAiScanSubtitle':
        'ఆన్ చేస్తే బిల్ ఫోటోలు AI గుర్తింపుకు సురక్షితంగా పంపవచ్చు. ప్రైవేట్ స్కాన్ అందుబాటులో ఉంటుంది.',
    'exportBackup': 'బ్యాకప్ ఫైల్ ఎక్స్‌పోర్ట్',
    'exportBackupSubtitle':
        'CartSense బ్యాకప్ JSON ఫైల్ సేవ్ లేదా షేర్ చేయండి.',
    'copyBackup': 'బ్యాకప్ టెక్స్ట్ కాపీ',
    'copyBackupSubtitle': 'షేర్ ఆప్షన్ అందుబాటులో లేనప్పుడు ఉపయోగకరం.',
    'restoreBackup': 'బ్యాకప్ టెక్స్ట్ నుండి రిస్టోర్',
    'restoreBackupSubtitle': 'మునుపటి CartSense బ్యాకప్ పేస్ట్ చేయండి.',
    'productMemory': 'ప్రోడక్ట్ మెమరీ',
    'clearProductMemory': 'ప్రోడక్ట్ మెమరీ క్లియర్',
    'about': 'గురించి',
    'showAppGuide': 'యాప్ గైడ్ చూపించండి',
  },
};
