import 'dart:async';

import 'package:shared_preferences/shared_preferences.dart';

import 'cloud_sync_service.dart';

class AppLanguage {
  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
  });

  final String code;
  final String name;
  final String nativeName;

  static const english = AppLanguage(
    code: 'en',
    name: 'English',
    nativeName: 'English',
  );
  static const hindi = AppLanguage(
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
  );
  static const telugu = AppLanguage(
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
  );

  static const values = [english, hindi, telugu];

  static AppLanguage byCode(String code) => values.firstWhere(
        (language) => language.code == code,
        orElse: () => english,
      );
}

class LanguageStore {
  static const _key = 'cartsense_language_code_v1';

  Future<AppLanguage> load() async {
    final preferences = await SharedPreferences.getInstance();
    return AppLanguage.byCode(preferences.getString(_key) ?? 'en');
  }

  Future<void> save(AppLanguage language) async {
    final preferences = await SharedPreferences.getInstance();
    await preferences.setString(_key, language.code);
    unawaited(CartSenseCloudSyncService.instance.pushProfileAndSettings());
  }
}

String appText(String languageCode, String key) {
  final handwrittenOverride = _handwrittenListText[languageCode]?[key];
  if (handwrittenOverride != null) return handwrittenOverride;
  final launchOverride = _launchTextOverrides[languageCode]?[key];
  if (launchOverride != null) return launchOverride;
  final supplemental = _supplementalTranslations[languageCode]?[key];
  if (supplemental != null) return supplemental;
  final localized = _translations[languageCode]?[key];
  if (localized != null) return localized;
  final supplementalEnglish = _supplementalTranslations['en']?[key];
  if (supplementalEnglish != null) return supplementalEnglish;
  return _translations['en']?[key] ?? key;
}

const _handwrittenListText = {
  'en': {
    'scanHandwrittenList': 'Scan handwritten list',
    'handwrittenListHelp':
        'Wrote the list on paper? Take a photo and review items before adding.',
    'takePaperListPhoto': 'Take paper-list photo',
    'takePaperListPhotoBody': 'Use camera for a handwritten shopping list.',
    'choosePaperListPhoto': 'Choose paper-list photo',
    'choosePaperListPhotoBody': 'Use a saved photo from gallery.',
    'readingPaperList': 'Reading your paper list...',
    'reviewPaperList': 'Review paper list',
    'reviewPaperListBody':
        'CartSense translated the handwriting to shopping items. Untick anything you do not want.',
    'writtenAs': 'Written as',
    'category': 'Category',
    'addSelectedItems': 'Add selected items',
    'paperItemsAdded': 'paper-list items added.',
    'paperListScanFailed':
        'Could not read this paper list. Try a clearer photo or type the list.',
    'noHandwrittenItemsFound': 'No handwritten grocery items found.',
  },
  'hi': {
    'scanHandwrittenList': 'लिखी हुई लिस्ट स्कैन करें',
    'handwrittenListHelp':
        'कागज पर लिस्ट लिखी है? फोटो लें और जोड़ने से पहले सामान चेक करें.',
    'takePaperListPhoto': 'पेपर लिस्ट की फोटो लें',
    'takePaperListPhotoBody':
        'हाथ से लिखी शॉपिंग लिस्ट के लिए कैमरा इस्तेमाल करें.',
    'choosePaperListPhoto': 'पेपर लिस्ट फोटो चुनें',
    'choosePaperListPhotoBody': 'गैलरी से सेव की हुई फोटो इस्तेमाल करें.',
    'readingPaperList': 'आपकी पेपर लिस्ट पढ़ रहे हैं...',
    'reviewPaperList': 'पेपर लिस्ट चेक करें',
    'reviewPaperListBody':
        'CartSense ने लिखी हुई लिस्ट को सामान में बदला है. जो नहीं चाहिए उसे untick करें.',
    'writtenAs': 'लिखा हुआ',
    'category': 'श्रेणी',
    'addSelectedItems': 'चुने हुए सामान जोड़ें',
    'paperItemsAdded': 'पेपर लिस्ट के सामान जुड़ गए.',
    'paperListScanFailed':
        'यह पेपर लिस्ट पढ़ नहीं पाए. साफ फोटो लें या लिस्ट टाइप करें.',
    'noHandwrittenItemsFound': 'हाथ से लिखे किराना सामान नहीं मिले.',
  },
  'te': {
    'scanHandwrittenList': 'రాసిన లిస్ట్ స్కాన్ చేయండి',
    'handwrittenListHelp':
        'కాగితం మీద లిస్ట్ రాశారా? ఫోటో తీసి, జోడించే ముందు వస్తువులు చూసుకోండి.',
    'takePaperListPhoto': 'పేపర్ లిస్ట్ ఫోటో తీయండి',
    'takePaperListPhotoBody': 'చేతిరాత షాపింగ్ లిస్ట్ కోసం కెమెరా వాడండి.',
    'choosePaperListPhoto': 'పేపర్ లిస్ట్ ఫోటో ఎంచుకోండి',
    'choosePaperListPhotoBody': 'గ్యాలరీలో ఉన్న ఫోటో వాడండి.',
    'readingPaperList': 'మీ పేపర్ లిస్ట్ చదువుతున్నాం...',
    'reviewPaperList': 'పేపర్ లిస్ట్ చూసుకోండి',
    'reviewPaperListBody':
        'CartSense చేతిరాతను షాపింగ్ వస్తువులుగా మార్చింది. అవసరం లేనివి untick చేయండి.',
    'writtenAs': 'రాసింది',
    'category': 'వర్గం',
    'addSelectedItems': 'ఎంచుకున్నవి జోడించండి',
    'paperItemsAdded': 'పేపర్ లిస్ట్ వస్తువులు జోడించాం.',
    'paperListScanFailed':
        'ఈ పేపర్ లిస్ట్ చదవలేకపోయాం. స్పష్టమైన ఫోటో తీసండి లేదా లిస్ట్ టైప్ చేయండి.',
    'noHandwrittenItemsFound': 'చేతిరాత గ్రోసరీ వస్తువులు కనిపించలేదు.',
  },
};

const _launchTextOverrides = {
  'en': {
    'scanReceipt': 'Scan bill',
    'longReceiptPhotos': 'Long bill',
    'productMaster': 'My usual items',
    'usualItemsBestPrices': 'Items you buy often and their latest prices',
    'aiScanUnavailable':
        'AI scan is not active in this install. Please use private scan or install the production build.',
    'useAiEnhancedScan': 'Use AI scan?',
    'aiConsentBody':
        'Your receipt photo is sent securely for reading. CartSense uses it only to read the bill. You can use private scan anytime.',
    'notNow': 'Not now',
    'agreeContinue': 'Agree and continue',
    'howScanBill': 'How do you want to scan?',
    'chooseEasiestBillOption': 'Choose the easiest option for your bill.',
    'takePhotoOfBill': 'Take bill photo',
    'normalGroceryBill': 'For a normal grocery bill',
    'longBillManyPhotos': 'Long bill / many photos',
    'forLongGroceryBills': 'For 30–40 item grocery bills',
    'chooseFromGallery': 'Choose from gallery',
    'existingBillPhoto': 'Use an existing bill photo',
    'billSavedPlanFirst':
        'Bill saved. Add items to Shopping before checkout to compare.',
    'checkoutChecked': 'Checkout checked',
    'bought': 'bought',
    'stillOnList': 'still on your list',
    'extra': 'extra',
    'monthlyBudget': 'Monthly grocery budget',
    'budgetExample': 'For example 10000',
    'saveBudget': 'Save budget',
    'saveBillFirstExport':
        'Save a bill first, then CartSense can export a report.',
    'exportReports': 'Export reports',
    'chooseReportFormat': 'Choose what you want to share or save.',
    'csvReport': 'CSV report',
    'excelSheets': 'Open in Excel or Google Sheets',
    'monthlyPdfReport': 'Monthly PDF report',
    'readableSummary': 'Readable summary for sharing',
    'whatsappSummary': 'WhatsApp summary',
    'shortTotalsCategories': 'Short message with totals and categories',
    'categoryChartImage': 'Category chart image',
    'shareCategoryImage': 'Share category spend as an image file',
    'fullExportBundle': 'Full export bundle',
    'reportsPlusBackup': 'Reports plus CartSense backup',
    'productsRemembered': 'Items CartSense remembers',
    'favorites': 'favorites',
    'categories': 'categories',
    'searchProducts': 'Search items',
    'searchProductsHint': 'Tea, oil, paneer, pads...',
    'showAllProducts': 'Show all items',
    'showFavorites': 'Show favorites',
    'allProducts': 'All items',
    'noProductsYet': 'No items yet',
    'noProductsYetBody':
        'Scan and save receipts first. Items you buy will appear here automatically.',
    'noProductsMatch':
        'No items match this view. Try another search or show all items.',
    'latest': 'Latest',
    'at': 'at',
    'boughtTimes': 'times bought',
    'removeFavorite': 'Remove favorite',
    'favorite': 'Favorite',
    'addToShopping': 'Add to Shopping',
    'open': 'Open',
    'reviewThisTrip': 'Review this trip',
    'plannedEstimate': 'Planned estimate',
    'billTotal': 'Bill total',
    'matched': 'matched',
    'stillNeeded': 'still needed',
    'unplanned': 'unplanned',
    'checkSuggestions':
        'We matched your saved list with this receipt. Check the suggestions before finishing.',
    'plannedProducts': 'Your planned products',
    'unplannedPurchases': 'Unplanned purchases',
    'finishTrip': 'Finish trip',
    'finishingTrip': 'Finishing trip…',
    'keepOnList': 'keep on list',
    'whatBoughtProduct': 'What did you buy for this product?',
    'notPurchased': 'Not purchased',
    'keepShoppingList': 'Keep it on the shopping list',
    'priceExpected': 'price as expected',
    'overEstimate': 'over estimate',
    'underEstimate': 'under estimate',
    'notFoundBill': 'Not found on this bill',
    'matchedLabel': 'Matched',
    'match': 'match',
    'change': 'Change',
  },
  'hi': {
    'scanReceipt': 'बिल स्कैन करें',
    'longReceiptPhotos': 'लंबा बिल',
    'productMaster': 'मेरे आम सामान',
    'usualItemsBestPrices': 'जो सामान आप अक्सर खरीदते हैं और उनकी ताज़ा कीमतें',
    'aiScanUnavailable':
        'इस इंस्टॉल में AI स्कैन चालू नहीं है। निजी स्कैन इस्तेमाल करें या प्रोडक्शन बिल्ड इंस्टॉल करें।',
    'useAiEnhancedScan': 'AI स्कैन इस्तेमाल करें?',
    'aiConsentBody':
        'बिल पढ़ने के लिए फोटो सुरक्षित रूप से भेजी जाती है। CartSense इसे सिर्फ बिल पढ़ने के लिए इस्तेमाल करता है। आप कभी भी निजी स्कैन इस्तेमाल कर सकते हैं।',
    'notNow': 'अभी नहीं',
    'agreeContinue': 'सहमत, आगे बढ़ें',
    'howScanBill': 'बिल कैसे स्कैन करना है?',
    'chooseEasiestBillOption': 'अपने बिल के लिए आसान विकल्प चुनें।',
    'takePhotoOfBill': 'बिल की फोटो लें',
    'normalGroceryBill': 'सामान्य किराना बिल के लिए',
    'longBillManyPhotos': 'लंबा बिल / कई फोटो',
    'forLongGroceryBills': '30–40 सामान वाले बिल के लिए',
    'chooseFromGallery': 'गैलरी से चुनें',
    'existingBillPhoto': 'पहले से मौजूद बिल फोटो इस्तेमाल करें',
    'billSavedPlanFirst':
        'बिल सेव हो गया। तुलना के लिए checkout से पहले Shopping में सामान जोड़ें।',
    'checkoutChecked': 'चेकआउट जाँच हो गई',
    'bought': 'खरीदा',
    'stillOnList': 'अभी भी सूची में',
    'extra': 'अतिरिक्त',
    'monthlyBudget': 'मासिक किराना बजट',
    'budgetExample': 'जैसे 10000',
    'saveBudget': 'बजट सेव करें',
    'saveBillFirstExport':
        'पहले एक बिल सेव करें, फिर CartSense रिपोर्ट बना सकेगा।',
    'exportReports': 'रिपोर्ट एक्सपोर्ट करें',
    'chooseReportFormat': 'शेयर या सेव करने का तरीका चुनें।',
    'csvReport': 'CSV रिपोर्ट',
    'excelSheets': 'Excel या Google Sheets में खोलें',
    'monthlyPdfReport': 'मासिक PDF रिपोर्ट',
    'readableSummary': 'शेयर करने योग्य साफ़ सारांश',
    'whatsappSummary': 'WhatsApp सारांश',
    'shortTotalsCategories': 'कुल और श्रेणी वाला छोटा संदेश',
    'categoryChartImage': 'श्रेणी चार्ट इमेज',
    'shareCategoryImage': 'श्रेणी खर्च को इमेज की तरह शेयर करें',
    'fullExportBundle': 'पूरा एक्सपोर्ट बंडल',
    'reportsPlusBackup': 'रिपोर्ट और CartSense बैकअप',
    'productsRemembered': 'CartSense को याद सामान',
    'favorites': 'पसंदीदा',
    'categories': 'श्रेणियाँ',
    'searchProducts': 'सामान खोजें',
    'searchProductsHint': 'चाय, तेल, पनीर, पैड...',
    'showAllProducts': 'सभी सामान दिखाएँ',
    'showFavorites': 'पसंदीदा दिखाएँ',
    'allProducts': 'सभी सामान',
    'noProductsYet': 'अभी सामान नहीं',
    'noProductsYetBody':
        'पहले बिल स्कैन और सेव करें। खरीदा हुआ सामान यहाँ अपने आप आएगा।',
    'noProductsMatch':
        'कोई सामान नहीं मिला। दूसरी खोज करें या सभी सामान दिखाएँ।',
    'latest': 'ताज़ा',
    'at': 'पर',
    'boughtTimes': 'बार खरीदा',
    'removeFavorite': 'पसंदीदा हटाएँ',
    'favorite': 'पसंदीदा',
    'addToShopping': 'Shopping में जोड़ें',
    'open': 'खोलें',
    'reviewThisTrip': 'इस खरीदारी की जाँच',
    'plannedEstimate': 'योजना अनुमान',
    'billTotal': 'बिल कुल',
    'matched': 'मिले',
    'stillNeeded': 'अभी चाहिए',
    'unplanned': 'बिना योजना',
    'checkSuggestions':
        'हमने आपकी सूची को इस बिल से मिलाया है। खत्म करने से पहले सुझाव देख लें।',
    'plannedProducts': 'आपकी योजना वाले सामान',
    'unplannedPurchases': 'अतिरिक्त खरीदे गए सामान',
    'finishTrip': 'खरीदारी पूरी करें',
    'finishingTrip': 'पूरा कर रहे हैं…',
    'keepOnList': 'सूची में रखें',
    'whatBoughtProduct': 'इस सामान के लिए आपने क्या खरीदा?',
    'notPurchased': 'नहीं खरीदा',
    'keepShoppingList': 'इसे shopping list में रखें',
    'priceExpected': 'कीमत उम्मीद जैसी',
    'overEstimate': 'अनुमान से ज़्यादा',
    'underEstimate': 'अनुमान से कम',
    'notFoundBill': 'इस बिल में नहीं मिला',
    'matchedLabel': 'मिलान',
    'match': 'मिलान',
    'change': 'बदलें',
  },
  'te': {
    'scanReceipt': 'బిల్ స్కాన్ చేయండి',
    'longReceiptPhotos': 'పొడవైన బిల్',
    'productMaster': 'నా సాధారణ వస్తువులు',
    'usualItemsBestPrices': 'మీరు తరచుగా కొనేవి మరియు తాజా ధరలు',
    'aiScanUnavailable':
        'ఈ ఇన్‌స్టాల్‌లో AI స్కాన్ యాక్టివ్‌గా లేదు. ప్రైవేట్ స్కాన్ వాడండి లేదా ప్రొడక్షన్ బిల్డ్ ఇన్‌స్టాల్ చేయండి.',
    'useAiEnhancedScan': 'AI స్కాన్ వాడాలా?',
    'aiConsentBody':
        'బిల్ చదవడానికి మీ ఫోటో సురక్షితంగా పంపబడుతుంది. CartSense దాన్ని బిల్ చదవడానికే వాడుతుంది. మీరు ఎప్పుడైనా ప్రైవేట్ స్కాన్ వాడవచ్చు.',
    'notNow': 'ఇప్పుడు కాదు',
    'agreeContinue': 'అంగీకరించి కొనసాగండి',
    'howScanBill': 'బిల్ ఎలా స్కాన్ చేయాలి?',
    'chooseEasiestBillOption': 'మీ బిల్‌కు సులభమైన ఎంపికను ఎంచుకోండి.',
    'takePhotoOfBill': 'బిల్ ఫోటో తీయండి',
    'normalGroceryBill': 'సాధారణ గ్రోసరీ బిల్ కోసం',
    'longBillManyPhotos': 'పొడవైన బిల్ / అనేక ఫోటోలు',
    'forLongGroceryBills': '30–40 వస్తువుల బిల్లుల కోసం',
    'chooseFromGallery': 'గ్యాలరీ నుంచి ఎంచుకోండి',
    'existingBillPhoto': 'ఇప్పటికే ఉన్న బిల్ ఫోటో వాడండి',
    'billSavedPlanFirst':
        'బిల్ సేవ్ అయింది. పోల్చడానికి checkout ముందు Shopping లో వస్తువులు జోడించండి.',
    'checkoutChecked': 'చెకౌట్ తనిఖీ అయింది',
    'bought': 'కొన్నవి',
    'stillOnList': 'ఇంకా లిస్ట్‌లో',
    'extra': 'అదనపు',
    'monthlyBudget': 'నెలవారీ గ్రోసరీ బడ్జెట్',
    'budgetExample': 'ఉదా: 10000',
    'saveBudget': 'బడ్జెట్ సేవ్ చేయండి',
    'saveBillFirstExport':
        'ముందు ఒక బిల్ సేవ్ చేయండి, తర్వాత CartSense రిపోర్ట్ ఎగుమతి చేస్తుంది.',
    'exportReports': 'రిపోర్టులు ఎగుమతి చేయండి',
    'chooseReportFormat': 'షేర్ లేదా సేవ్ చేయడానికి ఫార్మాట్ ఎంచుకోండి.',
    'csvReport': 'CSV రిపోర్ట్',
    'excelSheets': 'Excel లేదా Google Sheets లో తెరవండి',
    'monthlyPdfReport': 'నెలవారీ PDF రిపోర్ట్',
    'readableSummary': 'షేర్ చేయడానికి చదవగలిగే సారాంశం',
    'whatsappSummary': 'WhatsApp సారాంశం',
    'shortTotalsCategories': 'మొత్తాలు మరియు కేటగిరీల చిన్న సందేశం',
    'categoryChartImage': 'కేటగిరీ చార్ట్ ఇమేజ్',
    'shareCategoryImage': 'కేటగిరీ ఖర్చును ఇమేజ్‌గా షేర్ చేయండి',
    'fullExportBundle': 'పూర్తి ఎగుమతి బండిల్',
    'reportsPlusBackup': 'రిపోర్టులు మరియు CartSense బ్యాకప్',
    'productsRemembered': 'CartSense గుర్తుంచుకున్న వస్తువులు',
    'favorites': 'ఇష్టమైనవి',
    'categories': 'కేటగిరీలు',
    'searchProducts': 'వస్తువులు వెతకండి',
    'searchProductsHint': 'టీ, ఆయిల్, పనీర్, ప్యాడ్స్...',
    'showAllProducts': 'అన్ని వస్తువులు చూపండి',
    'showFavorites': 'ఇష్టమైనవి చూపండి',
    'allProducts': 'అన్ని వస్తువులు',
    'noProductsYet': 'ఇంకా వస్తువులు లేవు',
    'noProductsYetBody':
        'ముందు బిల్లులు స్కాన్ చేసి సేవ్ చేయండి. మీరు కొన్న వస్తువులు ఇక్కడ కనిపిస్తాయి.',
    'noProductsMatch': 'వస్తువులు దొరకలేదు. మరోసారి వెతకండి లేదా అన్నీ చూపండి.',
    'latest': 'తాజా',
    'at': 'వద్ద',
    'boughtTimes': 'సార్లు కొనారు',
    'removeFavorite': 'ఇష్టమైనది తొలగించండి',
    'favorite': 'ఇష్టమైనది',
    'addToShopping': 'Shopping లో జోడించండి',
    'open': 'తెరవండి',
    'reviewThisTrip': 'ఈ ట్రిప్ తనిఖీ',
    'plannedEstimate': 'ప్లాన్ అంచనా',
    'billTotal': 'బిల్ మొత్తం',
    'matched': 'మ్యాచ్ అయ్యాయి',
    'stillNeeded': 'ఇంకా కావాలి',
    'unplanned': 'ప్లాన్‌లో లేనివి',
    'checkSuggestions':
        'మీ సేవ్ చేసిన లిస్ట్‌ను ఈ బిల్‌తో పోల్చాము. ముగించే ముందు సూచనలు చూడండి.',
    'plannedProducts': 'మీ ప్లాన్ చేసిన వస్తువులు',
    'unplannedPurchases': 'అదనంగా కొన్నవి',
    'finishTrip': 'ట్రిప్ ముగించండి',
    'finishingTrip': 'ముగిస్తున్నాం…',
    'keepOnList': 'లిస్ట్‌లో ఉంచండి',
    'whatBoughtProduct': 'ఈ వస్తువు కోసం మీరు ఏమి కొనారు?',
    'notPurchased': 'కొనలేదు',
    'keepShoppingList': 'దాన్ని shopping list లో ఉంచండి',
    'priceExpected': 'ధర అంచనాలా ఉంది',
    'overEstimate': 'అంచనాకంటే ఎక్కువ',
    'underEstimate': 'అంచనాకంటే తక్కువ',
    'notFoundBill': 'ఈ బిల్‌లో దొరకలేదు',
    'matchedLabel': 'మ్యాచ్',
    'match': 'మ్యాచ్',
    'change': 'మార్చండి',
  },
};

String categoryText(String languageCode, String category) {
  final key = switch (category) {
    'Fruit & vegetables' => 'categoryProduce',
    'Dairy & chilled' => 'categoryDairy',
    'Cooking oils' => 'categoryCookingOils',
    'Tea & coffee' => 'categoryTeaCoffee',
    'Pantry staples' => 'categoryPantry',
    'Beverages' => 'categoryBeverages',
    'Snacks & sweets' => 'categorySnacks',
    'Breakfast & bakery' => 'categoryBreakfastBakery',
    'Frozen & ready foods' => 'categoryFrozenReady',
    'Household' => 'categoryHousehold',
    'Personal care' => 'categoryPersonalCare',
    'Sanitary care' => 'categorySanitaryCare',
    'Baby care' => 'categoryBabyCare',
    'Other' => 'categoryOther',
    _ => '',
  };
  return key.isEmpty ? category : appText(languageCode, key);
}

const _supplementalTranslations = {
  'en': {
    'shopping': 'Shopping',
    'bills': 'Bills',
    'spend': 'Spend',
    'skip': 'Skip',
    'continue': 'Continue',
    'startUsingCartSense': 'Start using CartSense',
    'onboardScanTitle': 'Scan grocery bills',
    'onboardScanBody':
        'Use AI Enhanced Scan for difficult receipts, or private on-device scan when you want everything to stay on your phone.',
    'onboardPlanTitle': 'Plan before shopping',
    'onboardPlanBody':
        'Create a shopping list, open Trip Mode in the store, tick items as you buy, then scan the checkout bill.',
    'onboardLearnTitle': 'CartSense learns with you',
    'onboardLearnBody':
        'When you approve or correct products, CartSense remembers categories locally so future scans become smarter.',
    'onboardPrivacyTitle': 'Your data, your control',
    'onboardPrivacyBody':
        'Receipts, lists, backups and product memory live on this phone unless you choose to export or share them.',
    'setUpHousehold': 'Set up your household',
    'householdSetupBody':
        'CartSense uses this only on this phone to estimate monthly grocery needs. You can skip it and fill it later.',
    'yourName': 'Your name',
    'preferredLanguage': 'Preferred language',
    'monthlyGroceryBudget': 'Monthly grocery budget',
    'totalFamilyMembers': 'Total family members',
    'male': 'Male',
    'female': 'Female',
    'children': 'Children',
    'seniors': 'Seniors',
    'myBills': 'My Bills',
    'mySpend': 'My Spend',
    'shoppingList': 'Shopping List',
    'scanNow': 'Scan now',
    'productMemory': 'Product memory',
    'noReceiptsYet': 'No receipts yet',
    'scanBill': 'Scan bill',
    'saved': 'Saved',
    'items': 'Items',
    'searchStoreProduct': 'Search store or product',
    'noBillsMatch': 'No bills match your search.',
    'paid': 'Paid',
    'viewBill': 'View bill',
    'there': 'there',
    'makeShoppingEasier': 'Let’s make shopping easier today.',
    'scanYourBill': 'Scan your bill',
    'readItemsPricesTotal':
        'CartSense will read items, prices and total for you.',
    'whatDoYouWant': 'What do you want to do?',
    'planTodayItems': 'Plan today’s items',
    'itemsToBuy': 'items to buy',
    'viewSavedBills': 'View saved bills',
    'billsSaved': 'bills saved',
    'seeWhereMoneyGoes': 'See where money goes',
    'invoiceNo': 'Invoice No',
    'youPaid': 'You Paid',
    'location': 'Location',
    'youSaved': 'You Saved',
    'yourShoppingRecord': 'Your shopping record',
    'totalPaid': 'Total paid',
    'noBillsSavedYet': 'No bills saved yet',
    'scanFirstBillSaveHere':
        'Scan your first bill. CartSense will save it here.',
    'householdProfile': 'Household profile',
    'householdProfileBody':
        'This helps CartSense estimate monthly essentials. You can change it anytime.',
    'householdProfileSaved':
        'Household profile saved. Suggestions will improve.',
    'monthlySuggestionsFor': 'Monthly suggestions are tuned for',
    'peopleAtHome': 'people in your home.',
    'addHouseholdSize':
        'Add household size once to make monthly essentials smarter.',
    'listOptions': 'List options',
    'clearPurchased': 'Clear purchased',
    'remaining': 'remaining',
    'purchased': 'purchased',
    'savedAutomaticallyDevice': 'Saved automatically on this device',
    'addProductsToList': 'Add products to list',
    'typeOneOrPasteList': 'Type one item, or paste the full grocery list.',
    'shoppingItems': 'Shopping items',
    'shoppingItemsHint': 'salt 1 packet, soaps dozen, paste',
    'speakShoppingList': 'Speak shopping list',
    'productActions': 'Product actions',
    'reminders': 'Reminders',
  },
  'hi': {
    'home': 'होम',
    'scan': 'स्कैन',
    'list': 'लिस्ट',
    'insights': 'इनसाइट्स',
    'shopping': 'खरीदारी',
    'bills': 'बिल',
    'spend': 'खर्च',
    'settings': 'सेटिंग्स',
    'account': 'खाता',
    'skip': 'छोड़ें',
    'continue': 'जारी रखें',
    'startUsingCartSense': 'CartSense शुरू करें',
    'onboardScanTitle': 'किराना बिल स्कैन करें',
    'onboardScanBody':
        'मुश्किल बिल के लिए AI स्कैन इस्तेमाल करें, या सब कुछ फोन पर रखना हो तो निजी स्कैन करें.',
    'onboardPlanTitle': 'खरीदारी से पहले योजना',
    'onboardPlanBody':
        'शॉपिंग लिस्ट बनाएं, स्टोर में Trip Mode खोलें, सामान कार्ट में डालते समय टिक करें, फिर checkout bill स्कैन करें.',
    'onboardLearnTitle': 'CartSense आपके साथ सीखता है',
    'onboardLearnBody':
        'जब आप सामान ठीक या approve करते हैं, CartSense category याद रखता है ताकि अगली scan बेहतर हो.',
    'onboardPrivacyTitle': 'आपका डेटा, आपका नियंत्रण',
    'onboardPrivacyBody':
        'बिल, लिस्ट, backup और product memory इसी फोन पर रहती है जब तक आप export या share न करें.',
    'setUpHousehold': 'परिवार सेट करें',
    'householdSetupBody':
        'CartSense monthly grocery needs अनुमान लगाने के लिए यह जानकारी इसी फोन पर इस्तेमाल करता है. आप इसे skip करके बाद में भर सकते हैं.',
    'yourName': 'आपका नाम',
    'preferredLanguage': 'पसंदीदा भाषा',
    'monthlyGroceryBudget': 'मासिक किराना बजट',
    'totalFamilyMembers': 'कुल परिवार सदस्य',
    'male': 'पुरुष',
    'female': 'महिला',
    'children': 'बच्चे',
    'seniors': 'वरिष्ठ',
    'myBills': 'मेरे बिल',
    'mySpend': 'मेरा खर्च',
    'shoppingList': 'शॉपिंग लिस्ट',
    'scanNow': 'अभी स्कैन करें',
    'productMemory': 'प्रोडक्ट मेमोरी',
    'noReceiptsYet': 'अभी कोई बिल नहीं',
    'scanBill': 'बिल स्कैन करें',
    'saved': 'बचत',
    'items': 'सामान',
    'searchStoreProduct': 'स्टोर या सामान खोजें',
    'noBillsMatch': 'आपकी खोज से कोई बिल नहीं मिला.',
    'paid': 'भुगतान',
    'viewBill': 'बिल देखें',
    'there': 'दोस्त',
    'makeShoppingEasier': 'आज की खरीदारी आसान बनाते हैं.',
    'scanYourBill': 'अपना बिल स्कैन करें',
    'readItemsPricesTotal':
        'CartSense आपके लिए सामान, कीमतें और कुल राशि पढ़ेगा.',
    'whatDoYouWant': 'आप क्या करना चाहते हैं?',
    'planTodayItems': 'आज की चीज़ें प्लान करें',
    'itemsToBuy': 'सामान खरीदने हैं',
    'viewSavedBills': 'सेव किए बिल देखें',
    'billsSaved': 'बिल सेव',
    'seeWhereMoneyGoes': 'पैसा कहाँ जा रहा है देखें',
    'invoiceNo': 'बिल नंबर',
    'youPaid': 'आपने भुगतान किया',
    'location': 'स्थान',
    'youSaved': 'आपने बचाया',
    'yourShoppingRecord': 'आपकी खरीदारी का रिकॉर्ड',
    'totalPaid': 'कुल भुगतान',
    'noBillsSavedYet': 'अभी कोई बिल सेव नहीं है',
    'scanFirstBillSaveHere':
        'अपना पहला बिल स्कैन करें. CartSense उसे यहाँ सेव करेगा.',
    'householdProfile': 'परिवार प्रोफाइल',
    'householdProfileBody':
        'इससे CartSense मासिक ज़रूरी सामान का अनुमान लगाता है. आप इसे कभी भी बदल सकते हैं.',
    'householdProfileSaved': 'परिवार प्रोफाइल सेव हो गई. सुझाव बेहतर होंगे.',
    'monthlySuggestionsFor': 'मासिक सुझाव',
    'peopleAtHome': 'लोगों के परिवार के हिसाब से हैं.',
    'addHouseholdSize':
        'मासिक ज़रूरी सामान बेहतर करने के लिए परिवार का आकार जोड़ें.',
    'listOptions': 'लिस्ट विकल्प',
    'clearPurchased': 'खरीदा हुआ साफ करें',
    'remaining': 'बाकी',
    'purchased': 'खरीदा',
    'savedAutomaticallyDevice': 'इस फोन पर अपने-आप सेव',
    'addProductsToList': 'लिस्ट में सामान जोड़ें',
    'typeOneOrPasteList':
        'एक सामान टाइप करें, या पूरी किराना लिस्ट paste करें.',
    'shoppingItems': 'शॉपिंग सामान',
    'shoppingItemsHint': 'नमक 1 पैकेट, साबुन दर्जन, पेस्ट',
    'speakShoppingList': 'शॉपिंग लिस्ट बोलें',
    'productActions': 'सामान विकल्प',
    'reminders': 'रिमाइंडर',
  },
  'te': {
    'home': 'హోమ్',
    'scan': 'స్కాన్',
    'list': 'లిస్ట్',
    'insights': 'ఇన్‌సైట్స్',
    'shopping': 'షాపింగ్',
    'bills': 'బిల్లులు',
    'spend': 'ఖర్చు',
    'settings': 'సెట్టింగ్స్',
    'account': 'ఖాతా',
    'skip': 'దాటవేయి',
    'continue': 'కొనసాగించు',
    'startUsingCartSense': 'CartSense ప్రారంభించండి',
    'onboardScanTitle': 'గ్రోసరీ బిల్లులు స్కాన్ చేయండి',
    'onboardScanBody':
        'కష్టమైన బిల్లులకు AI స్కాన్ వాడండి, లేదా అన్నీ మీ ఫోన్‌లోనే ఉండాలంటే ప్రైవేట్ స్కాన్ వాడండి.',
    'onboardPlanTitle': 'షాపింగ్ ముందు ప్లాన్ చేయండి',
    'onboardPlanBody':
        'షాపింగ్ లిస్ట్ తయారు చేయండి, స్టోర్‌లో Trip Mode తెరచి, కార్ట్‌లో వేసే వస్తువులను టిక్ చేయండి, తరువాత checkout bill స్కాన్ చేయండి.',
    'onboardLearnTitle': 'CartSense మీతో నేర్చుకుంటుంది',
    'onboardLearnBody':
        'మీరు వస్తువులను approve లేదా correct చేసినప్పుడు, CartSense categories గుర్తుంచుకుని తరువాత scans మెరుగుపరుస్తుంది.',
    'onboardPrivacyTitle': 'మీ డేటా, మీ నియంత్రణ',
    'onboardPrivacyBody':
        'బిల్లులు, లిస్ట్‌లు, backups మరియు product memory మీరు export/share చేసే వరకు ఈ ఫోన్‌లోనే ఉంటాయి.',
    'setUpHousehold': 'మీ కుటుంబాన్ని సెటప్ చేయండి',
    'householdSetupBody':
        'CartSense monthly grocery needs అంచనా వేయడానికి ఈ వివరాలను ఈ ఫోన్‌లో మాత్రమే వాడుతుంది. మీరు దాటవేసి తరువాత నింపవచ్చు.',
    'yourName': 'మీ పేరు',
    'preferredLanguage': 'ఇష్టమైన భాష',
    'monthlyGroceryBudget': 'నెలవారీ గ్రోసరీ బడ్జెట్',
    'totalFamilyMembers': 'మొత్తం కుటుంబ సభ్యులు',
    'male': 'పురుషులు',
    'female': 'మహిళలు',
    'children': 'పిల్లలు',
    'seniors': 'వృద్ధులు',
    'myBills': 'నా బిల్లులు',
    'mySpend': 'నా ఖర్చు',
    'shoppingList': 'షాపింగ్ లిస్ట్',
    'scanNow': 'ఇప్పుడు స్కాన్ చేయండి',
    'productMemory': 'ప్రోడక్ట్ మెమరీ',
    'noReceiptsYet': 'ఇంకా బిల్లులు లేవు',
    'scanBill': 'బిల్ స్కాన్ చేయండి',
    'saved': 'సేవింగ్',
    'items': 'వస్తువులు',
    'searchStoreProduct': 'స్టోర్ లేదా వస్తువు వెతకండి',
    'noBillsMatch': 'మీ శోధనకు బిల్లులు లేవు.',
    'paid': 'చెల్లించారు',
    'viewBill': 'బిల్ చూడండి',
    'there': 'మిత్రమా',
    'makeShoppingEasier': 'ఈరోజు షాపింగ్‌ను సులభం చేద్దాం.',
    'scanYourBill': 'మీ బిల్ స్కాన్ చేయండి',
    'readItemsPricesTotal':
        'CartSense మీ కోసం వస్తువులు, ధరలు మరియు మొత్తం చదువుతుంది.',
    'whatDoYouWant': 'మీరు ఏమి చేయాలనుకుంటున్నారు?',
    'planTodayItems': 'ఈరోజు వస్తువులు ప్లాన్ చేయండి',
    'itemsToBuy': 'వస్తువులు కొనాలి',
    'viewSavedBills': 'సేవ్ చేసిన బిల్లులు చూడండి',
    'billsSaved': 'బిల్లులు సేవ్',
    'seeWhereMoneyGoes': 'డబ్బు ఎక్కడ ఖర్చవుతోంది చూడండి',
    'invoiceNo': 'బిల్ నంబర్',
    'youPaid': 'మీరు చెల్లించారు',
    'location': 'స్థానం',
    'youSaved': 'మీరు సేవ్ చేసారు',
    'yourShoppingRecord': 'మీ షాపింగ్ రికార్డు',
    'totalPaid': 'మొత్తం చెల్లింపు',
    'noBillsSavedYet': 'ఇంకా బిల్లులు సేవ్ కాలేదు',
    'scanFirstBillSaveHere':
        'మీ మొదటి బిల్ స్కాన్ చేయండి. CartSense దాన్ని ఇక్కడ సేవ్ చేస్తుంది.',
    'householdProfile': 'కుటుంబ ప్రొఫైల్',
    'householdProfileBody':
        'దీనితో CartSense నెలవారీ అవసరమైన వస్తువులను అంచనా వేస్తుంది. మీరు ఎప్పుడైనా మార్చవచ్చు.',
    'householdProfileSaved':
        'కుటుంబ ప్రొఫైల్ సేవ్ అయింది. సూచనలు మెరుగుపడతాయి.',
    'monthlySuggestionsFor': 'నెలవారీ సూచనలు',
    'peopleAtHome': 'కుటుంబ సభ్యుల కోసం సరిపడేలా ఉన్నాయి.',
    'addHouseholdSize':
        'నెలవారీ అవసరాలను మెరుగుపరచడానికి కుటుంబ పరిమాణం జోడించండి.',
    'listOptions': 'లిస్ట్ ఎంపికలు',
    'clearPurchased': 'కొన్నవాటిని క్లియర్ చేయండి',
    'remaining': 'మిగిలినవి',
    'purchased': 'కొన్నవి',
    'savedAutomaticallyDevice': 'ఈ ఫోన్‌లో ఆటోమేటిక్‌గా సేవ్ అయింది',
    'addProductsToList': 'లిస్ట్‌లో వస్తువులు జోడించండి',
    'typeOneOrPasteList':
        'ఒక వస్తువు టైప్ చేయండి, లేదా మొత్తం గ్రోసరీ లిస్ట్ paste చేయండి.',
    'shoppingItems': 'షాపింగ్ వస్తువులు',
    'shoppingItemsHint': 'ఉప్పు 1 ప్యాకెట్, సబ్బులు డజన్, పేస్ట్',
    'speakShoppingList': 'షాపింగ్ లిస్ట్ మాట్లాడండి',
    'productActions': 'వస్తువు ఎంపికలు',
    'reminders': 'రిమైండర్లు',
  },
};

const _translations = {
  'en': {
    'home': 'Home',
    'scan': 'Scan',
    'list': 'List',
    'insights': 'Insights',
    'settings': 'Settings',
    'account': 'Account',
    'welcomeToCartSense': 'Welcome to CartSense',
    'loginFirstBody':
        'Sign in or create an account first. Then CartSense will guide you step by step.',
    'loginFirstFooter':
        'Simple setup now. Grocery planning, scanning and insights come next.',
    'hello': 'Hi',
    'readyNextTrip': 'Ready to plan, shop and save on your next grocery trip.',
    'signIn': 'Sign in',
    'signOut': 'Sign out',
    'signedIn': 'Signed in.',
    'signedOut': 'Signed out.',
    'email': 'Email',
    'password': 'Password',
    'createAccount': 'Create account',
    'newCreateOne': 'New to CartSense? Create an account',
    'alreadyHaveAccount': 'Already have an account? Sign in',
    'sendMagicLink': 'Send magic link instead',
    'magicLinkSent': 'Magic link sent. Check your email.',
    'continueWithGoogle': 'Continue with Google',
    'googleLoginFailed': 'Google login could not be started.',
    'phoneOtpLogin': 'Phone OTP login',
    'phoneNumber': 'Phone number',
    'otpCode': 'OTP code',
    'sendOtp': 'Send OTP',
    'verifyOtp': 'Verify OTP',
    'phoneOtpSent': 'OTP sent. Check SMS or WhatsApp.',
    'enterPhone': 'Enter phone number with country code.',
    'enterOtp': 'Enter the OTP code.',
    'enterEmail': 'Enter your email first.',
    'enterEmailPassword': 'Enter email and at least 6 character password.',
    'loginFailed': 'Login failed. Please try again.',
    'accountCreatedCheckEmail':
        'Account created. Check your email if confirmation is required.',
    'guestMode': 'Guest mode',
    'guestModeBody':
        'Use CartSense privately on this phone. Sign in when you want cloud backup and sync.',
    'guestOrCloudSync': 'Guest or cloud sync',
    'cloudAccount': 'Cloud account',
    'signedInAs': 'Signed in as',
    'cloudLoginNotConfigured': 'Cloud login is not configured in this build',
    'cloudLoginConfigBody':
        'Build with SUPABASE_URL and SUPABASE_ANON_KEY to enable sign in.',
    'guestModeAvailable': 'Guest mode stays available',
    'guestModeAvailableBody':
        'Scanning, shopping list and insights continue to work without login.',
    'cloudSyncComing': 'Cloud sync foundation',
    'cloudSyncComingBody':
        'Login is the first step. Receipt backup and family sync come next.',
    'cloudSyncActive': 'Cloud backup is active',
    'cloudSyncActiveBody':
        'Receipts, shopping list, family profile, budget and language sync quietly when you sign in.',
    'lastSynced': 'Last synced',
    'privateDataControl': 'You control private data',
    'privateDataControlBody':
        'Receipt and price sharing can stay off until you choose to enable it.',
    'cloudLoginActive': 'Cloud login active',
    'cloudLoginActiveBody':
        'CartSense is ready to back up your data when Supabase tables are available.',
    'language': 'Language',
    'chooseLanguage': 'Choose language',
    'languageSubtitle': 'English, Hindi and Telugu support.',
    'languageChanged': 'Language changed',
    'moreOptions': 'More options',
    'smartGroceryCompanion': 'Smart grocery companion',
    'scanGroceryReceipt': 'Scan a grocery receipt',
    'saveProductsPrices': 'Save products, prices and spending automatically.',
    'scanReceipt': 'Scan receipt',
    'longReceiptPhotos': 'Long receipt / multiple photos',
    'chooseAiOrPrivate': 'You choose AI or private on-device scan',
    'yourShortcuts': 'Your shortcuts',
    'budgetPriceTrends': 'Budget and price trends',
    'shoppingAssistant': 'Shopping Assistant',
    'planNextTrip': 'Plan your next trip',
    'productsToBuyCount': 'products to buy',
    'productMaster': 'Product master',
    'usualItemsBestPrices': 'Usual items, favorites and best prices',
    'recentReceipts': 'Recent receipts',
    'noSavedBillsMatch': 'No saved bills match your search.',
    'searchStoresItems': 'Search stores or grocery items',
    'clearSearch': 'Clear search',
    'privateScan': 'Private scan',
    'openSampleReceipt': 'Open sample receipt',
    'scanCheckoutBill': 'Scan your checkout bill',
    'compareWithList':
        'CartSense will compare this bill with your saved shopping list.',
    'aiScanCamera': 'AI scan with camera',
    'aiScanGallery': 'AI scan from gallery',
    'aiScanLong': 'AI scan long / multiple-page bill',
    'captureMultipleSections': 'Capture 2 to 4 top, middle and bottom photos.',
    'privateDeviceScan': 'Private on-device scan',
    'privateReader': 'Private on-device reader',
    'photoStaysPhone': 'The receipt photo stays on this phone.',
    'takePhoto': 'Take a photo',
    'chooseGallery': 'Choose from gallery',
    'estimatedBasket': 'Estimated basket',
    'startTrip': 'Start trip',
    'shareList': 'Share list',
    'smartTripAssistant': 'Smart trip assistant',
    'productsToBuy': 'Products to buy',
    'addProduct': 'Add product',
    'editProduct': 'Edit product',
    'productOrType': 'Product or product type',
    'forExampleTea': 'For example Tea',
    'scanShelfPrice': 'Scan shelf price label',
    'readingShelfPrice': 'Reading shelf price...',
    'shelfPriceCaptured': 'Shelf price captured',
    'quantity': 'Quantity',
    'unitPrice': 'Unit price',
    'category': 'Category',
    'categoryProduce': 'Fruit & vegetables',
    'categoryDairy': 'Dairy & chilled',
    'categoryCookingOils': 'Cooking oils',
    'categoryTeaCoffee': 'Tea & coffee',
    'categoryPantry': 'Pantry staples',
    'categoryBeverages': 'Beverages',
    'categorySnacks': 'Snacks & sweets',
    'categoryBreakfastBakery': 'Breakfast & bakery',
    'categoryFrozenReady': 'Frozen & ready foods',
    'categoryHousehold': 'Household',
    'categoryPersonalCare': 'Personal care',
    'categorySanitaryCare': 'Sanitary care',
    'categoryBabyCare': 'Baby care',
    'categoryOther': 'Other',
    'noteOptional': 'Note (optional)',
    'brandSizePreference': 'Brand, size or preference',
    'addReminder': 'Add reminder',
    'cancel': 'Cancel',
    'save': 'Save',
    'saveChanges': 'Save changes',
    'addToList': 'Add to list',
    'tripMode': 'Trip mode',
    'exit': 'Exit',
    'inStoreChecklist': 'In-store checklist',
    'stillToBuy': 'Still to buy',
    'inCart': 'In cart',
    'extraPicked': 'Extra picked in store',
    'checkoutScanBill': 'Checkout done — scan bill',
    'setTripBudget': 'Set trip budget',
    'addExtraItem': 'Add extra item',
    'beforeCounter': 'Before counter',
    'overBudget': 'over budget',
    'insideBudget': 'inside budget',
    'unknownPrices':
        'item prices are unknown. Scan shelf labels or type prices for a better counter estimate.',
    'expectedBillIncludes':
        'Expected bill includes checked planned items plus extras picked during this trip.',
    'removeToReduce': 'To reduce the bill, consider removing:',
    'remove': 'Remove',
    'priceUnknown': 'Price unknown',
    'savesAbout': 'Saves about',
    'backupRestore': 'Backup and restore',
    'appLanguage': 'App language',
    'privacy': 'Privacy',
    'allowAiScan': 'Allow AI Enhanced Scan',
    'allowAiScanSubtitle':
        'When enabled, receipt photos can be sent securely for AI recognition. Private scan remains available.',
    'exportBackup': 'Export backup file',
    'exportBackupSubtitle': 'Save or share a CartSense backup JSON file.',
    'copyBackup': 'Copy backup text',
    'copyBackupSubtitle': 'Useful if a share target is not available.',
    'restoreBackup': 'Restore from backup text',
    'restoreBackupSubtitle': 'Paste a previous CartSense backup.',
    'productMemory': 'Product memory',
    'clearProductMemory': 'Clear product memory',
    'about': 'About',
    'showAppGuide': 'Show app guide',
    'howShoppingAssistant': 'How to use Shopping Assistant',
    'planStep': '1. Plan',
    'planStepBody':
        'Add products before you leave. Your list is saved on this phone.',
    'shopStep': '2. Shop',
    'shopStepBody':
        'Open this list in the store and tick items as you put them in the cart.',
    'reconcileStep': '3. Scan & reconcile',
    'reconcileStepBody':
        'After checkout, scan the bill. CartSense will mark bought, missed and extra items.',
    'addProductField': 'Add a product',
    'addProductHint': 'Tea, milk, oil or a brand',
    'emptyShoppingList':
        'Add tea, milk, oil or any product above. CartSense saves the list here so you can open it at the store and tick items while shopping.',
    'noReceiptsYet': 'No receipts yet',
    'scanFirstReceiptBody':
        'Scan your first grocery receipt to start tracking prices and spending.',
    'scanFirstReceipt': 'Scan first receipt',
    'planList': 'Plan list',
    'tryDemo': 'Try demo',
    'exportGroceryReport': 'Export grocery report',
    'exportGroceryReportBody':
        'CSV, PDF, WhatsApp summary, category chart or full backup bundle.',
    'grocerySpendMonth': 'Grocery spend this month',
    'setBudget': 'Set budget',
    'edit': 'Edit',
    'savedBills': 'Saved bills',
    'possibleSaving': 'Possible saving',
    'spendingAlerts': 'Spending alerts',
    'spendingTrend': 'Spending trend',
    'categorySpend': 'Category spend',
    'thisMonth': 'This month',
    'allSavedBills': 'All saved bills',
    'storeComparison': 'Store comparison',
    'topExpensiveProducts': 'Top expensive products',
    'priceChanges': 'Price changes',
    'priceDrops': 'Price drops',
    'betterPricesNearby': 'Better prices nearby',
    'buyAgainSoon': 'Buy again soon',
    'scanAnotherMonth':
        'Scan another month of bills to see category increase alerts.',
    'saveBillsTrend': 'Save bills to start seeing spending trends.',
    'categoriesAppear': 'Categories will appear after you save a bill.',
    'storeSpendAppears': 'Store spend appears after you save receipts.',
    'productRankingAppears': 'Product spend ranking appears after scans.',
    'noPriceRises': 'No repeated product price rises found yet.',
    'priceDropsAppear':
        'Price drops will appear when repeated products get cheaper.',
    'scanMoreStores': 'Scan bills from more than one store to compare prices.',
    'repeatedProductsAppear':
        'Repeated products will appear here when CartSense predicts they may be due again.',
  },
  'hi': {
    'home': 'होम',
    'scan': 'स्कैन',
    'list': 'सूची',
    'insights': 'जानकारी',
    'settings': 'सेटिंग्स',
    'account': 'खाता',
    'signIn': 'साइन इन',
    'signOut': 'साइन आउट',
    'signedIn': 'साइन इन हो गया.',
    'signedOut': 'साइन आउट हो गया.',
    'email': 'ईमेल',
    'password': 'पासवर्ड',
    'createAccount': 'खाता बनाएं',
    'newCreateOne': 'CartSense में नए हैं? खाता बनाएं',
    'alreadyHaveAccount': 'पहले से खाता है? साइन इन करें',
    'sendMagicLink': 'मैजिक लिंक भेजें',
    'magicLinkSent': 'मैजिक लिंक भेजा गया. ईमेल देखें.',
    'continueWithGoogle': 'Google से जारी रखें',
    'googleLoginFailed': 'Google लॉगिन शुरू नहीं हुआ.',
    'phoneOtpLogin': 'फोन OTP लॉगिन',
    'phoneNumber': 'फोन नंबर',
    'otpCode': 'OTP कोड',
    'sendOtp': 'OTP भेजें',
    'verifyOtp': 'OTP सत्यापित करें',
    'phoneOtpSent': 'OTP भेजा गया. SMS या WhatsApp देखें.',
    'enterPhone': 'देश कोड के साथ फोन नंबर डालें.',
    'enterOtp': 'OTP कोड डालें.',
    'enterEmail': 'पहले ईमेल डालें.',
    'enterEmailPassword': 'ईमेल और कम से कम 6 अक्षर का पासवर्ड डालें.',
    'loginFailed': 'लॉगिन असफल. फिर कोशिश करें.',
    'accountCreatedCheckEmail': 'खाता बन गया. जरूरत हो तो ईमेल पुष्टि करें.',
    'guestMode': 'गेस्ट मोड',
    'guestModeBody':
        'CartSense को इस फोन पर निजी रूप से इस्तेमाल करें. क्लाउड बैकअप और सिंक के लिए साइन इन करें.',
    'guestOrCloudSync': 'गेस्ट या क्लाउड सिंक',
    'cloudAccount': 'क्लाउड खाता',
    'signedInAs': 'साइन इन',
    'cloudLoginNotConfigured': 'इस बिल्ड में क्लाउड लॉगिन कॉन्फ़िगर नहीं है',
    'cloudLoginConfigBody':
        'साइन इन चालू करने के लिए SUPABASE_URL और SUPABASE_ANON_KEY के साथ बिल्ड करें.',
    'guestModeAvailable': 'गेस्ट मोड उपलब्ध रहेगा',
    'guestModeAvailableBody':
        'स्कैन, शॉपिंग लिस्ट और इनसाइट्स बिना लॉगिन भी चलेंगे.',
    'cloudSyncComing': 'क्लाउड सिंक आधार',
    'cloudSyncComingBody':
        'लॉगिन पहला कदम है. रसीद बैकअप और परिवार सिंक आगे आएगा.',
    'cloudSyncActive': 'क्लाउड बैकअप चालू है',
    'cloudSyncActiveBody':
        'साइन इन रहने पर रसीदें, शॉपिंग लिस्ट, परिवार प्रोफाइल, बजट और भाषा अपने-आप सिंक होंगे.',
    'lastSynced': 'आखिरी सिंक',
    'privateDataControl': 'निजी डेटा आपके नियंत्रण में',
    'privateDataControlBody': 'रसीद और कीमत शेयरिंग आप चाहें तभी चालू होगी.',
    'cloudLoginActive': 'क्लाउड लॉगिन सक्रिय',
    'cloudLoginActiveBody':
        'Supabase टेबल उपलब्ध होने पर CartSense आपका डेटा बैकअप करने के लिए तैयार है.',
    'language': 'भाषा',
    'chooseLanguage': 'भाषा चुनें',
    'languageSubtitle': 'अंग्रेज़ी, हिन्दी और तेलुगु समर्थन.',
    'languageChanged': 'भाषा बदली गई',
    'moreOptions': 'और विकल्प',
    'smartGroceryCompanion': 'स्मार्ट किराना साथी',
    'scanGroceryReceipt': 'किराना बिल स्कैन करें',
    'saveProductsPrices': 'सामान, कीमतें और खर्च अपने आप सेव करें.',
    'scanReceipt': 'बिल स्कैन करें',
    'longReceiptPhotos': 'लंबा बिल / कई फोटो',
    'chooseAiOrPrivate': 'AI या निजी ऑन-डिवाइस स्कैन चुनें',
    'yourShortcuts': 'आपके शॉर्टकट',
    'budgetPriceTrends': 'बजट और कीमत रुझान',
    'shoppingAssistant': 'खरीदारी सहायक',
    'planNextTrip': 'अगली खरीदारी की योजना',
    'productsToBuyCount': 'सामान खरीदने हैं',
    'productMaster': 'प्रोडक्ट मास्टर',
    'usualItemsBestPrices': 'आम सामान, पसंदीदा और अच्छी कीमतें',
    'recentReceipts': 'हाल के बिल',
    'noSavedBillsMatch': 'आपकी खोज से कोई सेव बिल नहीं मिला.',
    'searchStoresItems': 'स्टोर या सामान खोजें',
    'clearSearch': 'खोज साफ करें',
    'privateScan': 'निजी स्कैन',
    'openSampleReceipt': 'नमूना बिल खोलें',
    'scanCheckoutBill': 'चेकआउट बिल स्कैन करें',
    'compareWithList':
        'CartSense इस बिल की तुलना आपकी सेव खरीदारी सूची से करेगा.',
    'aiScanCamera': 'कैमरा से AI स्कैन',
    'aiScanGallery': 'गैलरी से AI स्कैन',
    'aiScanLong': 'लंबे / कई पेज बिल का AI स्कैन',
    'captureMultipleSections': 'ऊपर, बीच और नीचे के 2 से 4 फोटो लें.',
    'privateDeviceScan': 'निजी ऑन-डिवाइस स्कैन',
    'privateReader': 'निजी ऑन-डिवाइस रीडर',
    'photoStaysPhone': 'बिल की फोटो इसी फोन पर रहती है.',
    'takePhoto': 'फोटो लें',
    'chooseGallery': 'गैलरी से चुनें',
    'estimatedBasket': 'अनुमानित बिल',
    'startTrip': 'खरीदारी शुरू करें',
    'shareList': 'सूची शेयर करें',
    'smartTripAssistant': 'स्मार्ट खरीदारी सहायक',
    'productsToBuy': 'खरीदने वाला सामान',
    'addProduct': 'सामान जोड़ें',
    'editProduct': 'सामान बदलें',
    'productOrType': 'सामान या प्रकार',
    'forExampleTea': 'जैसे चाय',
    'scanShelfPrice': 'शेल्फ कीमत स्कैन करें',
    'readingShelfPrice': 'शेल्फ कीमत पढ़ रहे हैं...',
    'shelfPriceCaptured': 'शेल्फ कीमत कैप्चर हुई',
    'quantity': 'मात्रा',
    'unitPrice': 'प्रति यूनिट कीमत',
    'category': 'श्रेणी',
    'categoryProduce': 'फल और सब्जियाँ',
    'categoryDairy': 'डेयरी और ठंडे सामान',
    'categoryCookingOils': 'खाना पकाने के तेल',
    'categoryTeaCoffee': 'चाय और कॉफी',
    'categoryPantry': 'रसोई के जरूरी सामान',
    'categoryBeverages': 'पेय पदार्थ',
    'categorySnacks': 'नाश्ता और मिठाई',
    'categoryBreakfastBakery': 'नाश्ता और बेकरी',
    'categoryFrozenReady': 'फ्रोजन और तैयार खाद्य',
    'categoryHousehold': 'घर की सफाई',
    'categoryPersonalCare': 'व्यक्तिगत देखभाल',
    'categorySanitaryCare': 'सैनिटरी देखभाल',
    'categoryBabyCare': 'बच्चों की देखभाल',
    'categoryOther': 'अन्य',
    'noteOptional': 'नोट (वैकल्पिक)',
    'brandSizePreference': 'ब्रांड, साइज या पसंद',
    'addReminder': 'रिमाइंडर जोड़ें',
    'cancel': 'रद्द करें',
    'save': 'सेव',
    'saveChanges': 'बदलाव सेव करें',
    'addToList': 'सूची में जोड़ें',
    'tripMode': 'स्टोर मोड',
    'exit': 'बाहर जाएं',
    'inStoreChecklist': 'स्टोर चेकलिस्ट',
    'stillToBuy': 'अभी खरीदना है',
    'inCart': 'कार्ट में',
    'extraPicked': 'स्टोर में अतिरिक्त लिया',
    'checkoutScanBill': 'बिल हो गया — स्कैन करें',
    'setTripBudget': 'ट्रिप बजट सेट करें',
    'addExtraItem': 'अतिरिक्त सामान जोड़ें',
    'beforeCounter': 'काउंटर से पहले',
    'overBudget': 'बजट से ऊपर',
    'insideBudget': 'बजट में',
    'unknownPrices':
        'सामान की कीमत अज्ञात है. बेहतर अनुमान के लिए शेल्फ लेबल स्कैन करें या कीमत लिखें.',
    'expectedBillIncludes':
        'अनुमानित बिल में चुने हुए सामान और ट्रिप में लिए अतिरिक्त सामान शामिल हैं.',
    'removeToReduce': 'बिल कम करने के लिए हटाने पर विचार करें:',
    'remove': 'हटाएं',
    'priceUnknown': 'कीमत अज्ञात',
    'savesAbout': 'लगभग बचत',
    'backupRestore': 'बैकअप और रिस्टोर',
    'appLanguage': 'ऐप भाषा',
    'privacy': 'प्राइवेसी',
    'allowAiScan': 'AI Enhanced Scan की अनुमति दें',
    'allowAiScanSubtitle':
        'चालू होने पर बिल फोटो सुरक्षित रूप से AI पहचान के लिए भेजी जा सकती है. निजी स्कैन उपलब्ध रहेगा.',
    'exportBackup': 'बैकअप फाइल एक्सपोर्ट करें',
    'exportBackupSubtitle': 'CartSense बैकअप JSON फाइल सेव या शेयर करें.',
    'copyBackup': 'बैकअप टेक्स्ट कॉपी करें',
    'copyBackupSubtitle': 'जब शेयर विकल्प उपलब्ध न हो तो उपयोगी.',
    'restoreBackup': 'बैकअप टेक्स्ट से रिस्टोर करें',
    'restoreBackupSubtitle': 'पुराना CartSense बैकअप पेस्ट करें.',
    'productMemory': 'प्रोडक्ट मेमोरी',
    'clearProductMemory': 'प्रोडक्ट मेमोरी साफ करें',
    'about': 'ऐप के बारे में',
    'showAppGuide': 'ऐप गाइड दिखाएं',
    'howShoppingAssistant': 'खरीदारी सहायक कैसे इस्तेमाल करें',
    'planStep': '1. योजना',
    'planStepBody':
        'घर से निकलने से पहले सामान जोड़ें. आपकी सूची इस फोन पर सेव रहती है.',
    'shopStep': '2. खरीदारी',
    'shopStepBody':
        'स्टोर में यह सूची खोलें और सामान कार्ट में डालते समय टिक करें.',
    'reconcileStep': '3. स्कैन और मिलान',
    'reconcileStepBody':
        'चेकआउट के बाद बिल स्कैन करें. CartSense खरीदा, छूटा और अतिरिक्त सामान दिखाएगा.',
    'addProductField': 'सामान जोड़ें',
    'addProductHint': 'चाय, दूध, तेल या ब्रांड',
    'emptyShoppingList':
        'ऊपर चाय, दूध, तेल या कोई भी सामान जोड़ें. CartSense सूची को सेव रखता है ताकि आप स्टोर में खोलकर सामान टिक कर सकें.',
    'noReceiptsYet': 'अभी कोई बिल नहीं',
    'scanFirstReceiptBody':
        'कीमत और खर्च ट्रैक करने के लिए पहला किराना बिल स्कैन करें.',
    'scanFirstReceipt': 'पहला बिल स्कैन करें',
    'planList': 'सूची बनाएं',
    'tryDemo': 'डेमो देखें',
    'exportGroceryReport': 'किराना रिपोर्ट एक्सपोर्ट करें',
    'exportGroceryReportBody':
        'CSV, PDF, WhatsApp सारांश, श्रेणी चार्ट या पूरा बैकअप.',
    'grocerySpendMonth': 'इस महीने का किराना खर्च',
    'setBudget': 'बजट सेट करें',
    'edit': 'बदलें',
    'savedBills': 'सेव बिल',
    'possibleSaving': 'संभावित बचत',
    'spendingAlerts': 'खर्च अलर्ट',
    'spendingTrend': 'खर्च रुझान',
    'categorySpend': 'श्रेणी खर्च',
    'thisMonth': 'इस महीने',
    'allSavedBills': 'सभी सेव बिल',
    'storeComparison': 'स्टोर तुलना',
    'topExpensiveProducts': 'सबसे महंगे सामान',
    'priceChanges': 'कीमत बदलाव',
    'priceDrops': 'कीमत गिरावट',
    'betterPricesNearby': 'पास में बेहतर कीमतें',
    'buyAgainSoon': 'जल्द फिर खरीदें',
    'scanAnotherMonth':
        'श्रेणी बढ़ोतरी अलर्ट देखने के लिए दूसरे महीने के बिल स्कैन करें.',
    'saveBillsTrend': 'खर्च रुझान देखने के लिए बिल सेव करें.',
    'categoriesAppear': 'बिल सेव करने के बाद श्रेणियां दिखेंगी.',
    'storeSpendAppears': 'बिल सेव करने के बाद स्टोर खर्च दिखेगा.',
    'productRankingAppears': 'स्कैन के बाद सामान खर्च रैंकिंग दिखेगी.',
    'noPriceRises': 'अभी दोहराए गए सामान की कीमत बढ़ोतरी नहीं मिली.',
    'priceDropsAppear': 'दोहराए गए सामान सस्ते होने पर कीमत गिरावट दिखेगी.',
    'scanMoreStores':
        'कीमतों की तुलना के लिए एक से अधिक स्टोर के बिल स्कैन करें.',
    'repeatedProductsAppear':
        'जब CartSense अनुमान लगाएगा कि सामान फिर खरीदना है, वे यहां दिखेंगे.',
  },
  'te': {
    'home': 'హోమ్',
    'scan': 'స్కాన్',
    'list': 'లిస్ట్',
    'insights': 'ఇన్‌సైట్స్',
    'settings': 'సెట్టింగ్స్',
    'account': 'ఖాతా',
    'signIn': 'సైన్ ఇన్',
    'signOut': 'సైన్ అవుట్',
    'signedIn': 'సైన్ ఇన్ అయింది.',
    'signedOut': 'సైన్ అవుట్ అయింది.',
    'email': 'ఇమెయిల్',
    'password': 'పాస్‌వర్డ్',
    'createAccount': 'ఖాతా సృష్టించండి',
    'newCreateOne': 'CartSenseకి కొత్తవారా? ఖాతా సృష్టించండి',
    'alreadyHaveAccount': 'ఖాతా ఉందా? సైన్ ఇన్ చేయండి',
    'sendMagicLink': 'మ్యాజిక్ లింక్ పంపండి',
    'magicLinkSent': 'మ్యాజిక్ లింక్ పంపబడింది. ఇమెయిల్ చూడండి.',
    'continueWithGoogle': 'Googleతో కొనసాగండి',
    'googleLoginFailed': 'Google లాగిన్ ప్రారంభించలేకపోయింది.',
    'phoneOtpLogin': 'ఫోన్ OTP లాగిన్',
    'phoneNumber': 'ఫోన్ నంబర్',
    'otpCode': 'OTP కోడ్',
    'sendOtp': 'OTP పంపండి',
    'verifyOtp': 'OTP ధృవీకరించండి',
    'phoneOtpSent': 'OTP పంపబడింది. SMS లేదా WhatsApp చూడండి.',
    'enterPhone': 'దేశ కోడ్‌తో ఫోన్ నంబర్ ఇవ్వండి.',
    'enterOtp': 'OTP కోడ్ ఇవ్వండి.',
    'enterEmail': 'ముందుగా ఇమెయిల్ ఇవ్వండి.',
    'enterEmailPassword': 'ఇమెయిల్ మరియు కనీసం 6 అక్షరాల పాస్‌వర్డ్ ఇవ్వండి.',
    'loginFailed': 'లాగిన్ విఫలమైంది. మళ్లీ ప్రయత్నించండి.',
    'accountCreatedCheckEmail':
        'ఖాతా సృష్టించబడింది. అవసరమైతే ఇమెయిల్ నిర్ధారించండి.',
    'guestMode': 'గెస్ట్ మోడ్',
    'guestModeBody':
        'CartSenseని ఈ ఫోన్‌లో ప్రైవేట్‌గా వాడండి. క్లౌడ్ బ్యాకప్ మరియు సింక్ కోసం సైన్ ఇన్ చేయండి.',
    'guestOrCloudSync': 'గెస్ట్ లేదా క్లౌడ్ సింక్',
    'cloudAccount': 'క్లౌడ్ ఖాతా',
    'signedInAs': 'సైన్ ఇన్',
    'cloudLoginNotConfigured': 'ఈ బిల్డ్‌లో క్లౌడ్ లాగిన్ కాన్ఫిగర్ కాలేదు',
    'cloudLoginConfigBody':
        'సైన్ ఇన్ ప్రారంభించడానికి SUPABASE_URL మరియు SUPABASE_ANON_KEYతో బిల్డ్ చేయండి.',
    'guestModeAvailable': 'గెస్ట్ మోడ్ అందుబాటులో ఉంటుంది',
    'guestModeAvailableBody':
        'స్కాన్, షాపింగ్ లిస్ట్ మరియు ఇన్‌సైట్స్ లాగిన్ లేకుండానే పనిచేస్తాయి.',
    'cloudSyncComing': 'క్లౌడ్ సింక్ ఫౌండేషన్',
    'cloudSyncComingBody':
        'లాగిన్ మొదటి దశ. రసీదు బ్యాకప్ మరియు కుటుంబ సింక్ తరువాత వస్తాయి.',
    'cloudSyncActive': 'క్లౌడ్ బ్యాకప్ యాక్టివ్',
    'cloudSyncActiveBody':
        'సైన్ ఇన్ చేసినప్పుడు రసీదులు, షాపింగ్ లిస్ట్, కుటుంబ ప్రొఫైల్, బడ్జెట్ మరియు భాష నిశ్శబ్దంగా సింక్ అవుతాయి.',
    'lastSynced': 'చివరిగా సింక్',
    'privateDataControl': 'ప్రైవేట్ డేటా మీ నియంత్రణలో',
    'privateDataControlBody':
        'రసీదు మరియు ధర షేరింగ్ మీరు ఎంచుకున్నప్పుడు మాత్రమే ఆన్ అవుతుంది.',
    'cloudLoginActive': 'క్లౌడ్ లాగిన్ యాక్టివ్',
    'cloudLoginActiveBody':
        'Supabase టేబుల్స్ అందుబాటులో ఉన్నప్పుడు CartSense మీ డేటాను బ్యాకప్ చేయడానికి సిద్ధంగా ఉంది.',
    'language': 'భాష',
    'chooseLanguage': 'భాష ఎంచుకోండి',
    'languageSubtitle': 'ఇంగ్లీష్, హిందీ మరియు తెలుగు మద్దతు.',
    'languageChanged': 'భాష మార్చబడింది',
    'moreOptions': 'మరిన్ని ఎంపికలు',
    'smartGroceryCompanion': 'స్మార్ట్ గ్రోసరీ సహాయకుడు',
    'scanGroceryReceipt': 'గ్రోసరీ బిల్ స్కాన్ చేయండి',
    'saveProductsPrices':
        'వస్తువులు, ధరలు మరియు ఖర్చు ఆటోమేటిక్‌గా సేవ్ చేయండి.',
    'scanReceipt': 'బిల్ స్కాన్',
    'longReceiptPhotos': 'పొడవైన బిల్ / అనేక ఫోటోలు',
    'chooseAiOrPrivate': 'AI లేదా ప్రైవేట్ ఆన్-డివైస్ స్కాన్ ఎంచుకోండి',
    'yourShortcuts': 'మీ షార్ట్‌కట్లు',
    'budgetPriceTrends': 'బడ్జెట్ మరియు ధరల ట్రెండ్స్',
    'shoppingAssistant': 'షాపింగ్ అసిస్టెంట్',
    'planNextTrip': 'తర్వాతి షాపింగ్ ప్లాన్',
    'productsToBuyCount': 'వస్తువులు కొనాలి',
    'productMaster': 'ప్రోడక్ట్ మాస్టర్',
    'usualItemsBestPrices': 'సాధారణ వస్తువులు, ఇష్టమైనవి మరియు మంచి ధరలు',
    'recentReceipts': 'ఇటీవలి బిల్లులు',
    'noSavedBillsMatch': 'మీ శోధనకు సేవ్ చేసిన బిల్లులు లేవు.',
    'searchStoresItems': 'స్టోర్‌లు లేదా వస్తువులు వెతకండి',
    'clearSearch': 'శోధన క్లియర్',
    'privateScan': 'ప్రైవేట్ స్కాన్',
    'openSampleReceipt': 'నమూనా బిల్ తెరవండి',
    'scanCheckoutBill': 'చెకౌట్ బిల్ స్కాన్ చేయండి',
    'compareWithList':
        'CartSense ఈ బిల్లును మీ సేవ్ చేసిన షాపింగ్ లిస్ట్‌తో పోలుస్తుంది.',
    'aiScanCamera': 'కెమెరాతో AI స్కాన్',
    'aiScanGallery': 'గ్యాలరీ నుండి AI స్కాన్',
    'aiScanLong': 'పొడవైన / అనేక పేజీ బిల్ AI స్కాన్',
    'captureMultipleSections':
        'పై, మధ్య, కింది భాగాల 2 నుండి 4 ఫోటోలు తీసుకోండి.',
    'privateDeviceScan': 'ప్రైవేట్ ఆన్-డివైస్ స్కాన్',
    'privateReader': 'ప్రైవేట్ ఆన్-డివైస్ రీడర్',
    'photoStaysPhone': 'బిల్ ఫోటో ఈ ఫోన్‌లోనే ఉంటుంది.',
    'takePhoto': 'ఫోటో తీయండి',
    'chooseGallery': 'గ్యాలరీ నుండి ఎంచుకోండి',
    'estimatedBasket': 'అంచనా బిల్',
    'startTrip': 'షాపింగ్ మొదలుపెట్టు',
    'shareList': 'లిస్ట్ షేర్',
    'smartTripAssistant': 'స్మార్ట్ షాపింగ్ అసిస్టెంట్',
    'productsToBuy': 'కొనాల్సిన వస్తువులు',
    'addProduct': 'వస్తువు జోడించండి',
    'editProduct': 'వస్తువు మార్చండి',
    'productOrType': 'వస్తువు లేదా రకం',
    'forExampleTea': 'ఉదాహరణకు టీ',
    'scanShelfPrice': 'షెల్ఫ్ ధర స్కాన్ చేయండి',
    'readingShelfPrice': 'షెల్ఫ్ ధర చదువుతోంది...',
    'shelfPriceCaptured': 'షెల్ఫ్ ధర క్యాప్చర్ అయింది',
    'quantity': 'పరిమాణం',
    'unitPrice': 'యూనిట్ ధర',
    'category': 'కేటగిరీ',
    'categoryProduce': 'పండ్లు & కూరగాయలు',
    'categoryDairy': 'డెయిరీ & చల్లని వస్తువులు',
    'categoryCookingOils': 'వంట నూనెలు',
    'categoryTeaCoffee': 'టీ & కాఫీ',
    'categoryPantry': 'వంటగది అవసరాలు',
    'categoryBeverages': 'పానీయాలు',
    'categorySnacks': 'స్నాక్స్ & స్వీట్స్',
    'categoryBreakfastBakery': 'బ్రేక్‌ఫాస్ట్ & బేకరీ',
    'categoryFrozenReady': 'ఫ్రోజెన్ & రెడీ ఫుడ్స్',
    'categoryHousehold': 'ఇంటి శుభ్రత',
    'categoryPersonalCare': 'వ్యక్తిగత సంరక్షణ',
    'categorySanitaryCare': 'సానిటరీ సంరక్షణ',
    'categoryBabyCare': 'బేబీ కేర్',
    'categoryOther': 'ఇతర',
    'noteOptional': 'నోట్ (ఐచ్చికం)',
    'brandSizePreference': 'బ్రాండ్, సైజు లేదా అభిరుచి',
    'addReminder': 'రిమైండర్ జోడించండి',
    'cancel': 'రద్దు',
    'save': 'సేవ్',
    'saveChanges': 'మార్పులు సేవ్',
    'addToList': 'లిస్ట్‌లో జోడించండి',
    'tripMode': 'స్టోర్ మోడ్',
    'exit': 'బయటకు',
    'inStoreChecklist': 'స్టోర్ చెక్‌లిస్ట్',
    'stillToBuy': 'ఇంకా కొనాల్సినవి',
    'inCart': 'కార్ట్‌లో',
    'extraPicked': 'స్టోర్‌లో అదనంగా తీసుకున్నవి',
    'checkoutScanBill': 'బిల్ అయింది — స్కాన్ చేయండి',
    'setTripBudget': 'ట్రిప్ బడ్జెట్ సెట్ చేయండి',
    'addExtraItem': 'అదనపు వస్తువు జోడించండి',
    'beforeCounter': 'కౌంటర్ ముందు',
    'overBudget': 'బడ్జెట్ దాటింది',
    'insideBudget': 'బడ్జెట్‌లో ఉంది',
    'unknownPrices':
        'వస్తువుల ధరలు తెలియదు. మంచి అంచనాకు షెల్ఫ్ లేబుల్ స్కాన్ చేయండి లేదా ధర టైప్ చేయండి.',
    'expectedBillIncludes':
        'అంచనా బిల్‌లో చెక్ చేసిన వస్తువులు మరియు ట్రిప్‌లో తీసుకున్న అదనపు వస్తువులు ఉంటాయి.',
    'removeToReduce': 'బిల్ తగ్గించడానికి వీటిని తీసేయండి:',
    'remove': 'తీసేయండి',
    'priceUnknown': 'ధర తెలియదు',
    'savesAbout': 'సుమారు ఆదా',
    'backupRestore': 'బ్యాకప్ మరియు రిస్టోర్',
    'appLanguage': 'యాప్ భాష',
    'privacy': 'ప్రైవసీ',
    'allowAiScan': 'AI Enhanced Scan అనుమతించండి',
    'allowAiScanSubtitle':
        'ఆన్ చేస్తే బిల్ ఫోటోలు AI గుర్తింపుకు సురక్షితంగా పంపవచ్చు. ప్రైవేట్ స్కాన్ అందుబాటులో ఉంటుంది.',
    'exportBackup': 'బ్యాకప్ ఫైల్ ఎక్స్‌పోర్ట్',
    'exportBackupSubtitle':
        'CartSense బ్యాకప్ JSON ఫైల్ సేవ్ లేదా షేర్ చేయండి.',
    'copyBackup': 'బ్యాకప్ టెక్స్ట్ కాపీ',
    'copyBackupSubtitle': 'షేర్ ఆప్షన్ అందుబాటులో లేనప్పుడు ఉపయోగకరం.',
    'restoreBackup': 'బ్యాకప్ టెక్స్ట్ నుండి రిస్టోర్',
    'restoreBackupSubtitle': 'మునుపటి CartSense బ్యాకప్ పేస్ట్ చేయండి.',
    'productMemory': 'ప్రోడక్ట్ మెమరీ',
    'clearProductMemory': 'ప్రోడక్ట్ మెమరీ క్లియర్',
    'about': 'గురించి',
    'showAppGuide': 'యాప్ గైడ్ చూపించండి',
    'howShoppingAssistant': 'షాపింగ్ అసిస్టెంట్ ఎలా వాడాలి',
    'planStep': '1. ప్లాన్',
    'planStepBody':
        'బయటకు వెళ్లే ముందు వస్తువులు జోడించండి. మీ లిస్ట్ ఈ ఫోన్‌లో సేవ్ అవుతుంది.',
    'shopStep': '2. షాప్',
    'shopStepBody':
        'స్టోర్‌లో ఈ లిస్ట్ తెరిచి, కార్ట్‌లో వేసినప్పుడు టిక్ చేయండి.',
    'reconcileStep': '3. స్కాన్ & పోల్చండి',
    'reconcileStepBody':
        'చెకౌట్ తర్వాత బిల్ స్కాన్ చేయండి. CartSense కొనినవి, మిస్సైనవి, అదనపు వస్తువులు చూపిస్తుంది.',
    'addProductField': 'వస్తువు జోడించండి',
    'addProductHint': 'టీ, పాలు, నూనె లేదా బ్రాండ్',
    'emptyShoppingList':
        'పై భాగంలో టీ, పాలు, నూనె లేదా ఏ వస్తువైనా జోడించండి. స్టోర్‌లో తెరిచి టిక్ చేయడానికి CartSense లిస్ట్‌ను సేవ్ చేస్తుంది.',
    'noReceiptsYet': 'ఇంకా బిల్లులు లేవు',
    'scanFirstReceiptBody':
        'ధరలు మరియు ఖర్చు ట్రాక్ చేయడానికి మొదటి గ్రోసరీ బిల్ స్కాన్ చేయండి.',
    'scanFirstReceipt': 'మొదటి బిల్ స్కాన్',
    'planList': 'లిస్ట్ ప్లాన్',
    'tryDemo': 'డెమో చూడండి',
    'exportGroceryReport': 'గ్రోసరీ రిపోర్ట్ ఎక్స్‌పోర్ట్',
    'exportGroceryReportBody':
        'CSV, PDF, WhatsApp సారాంశం, కేటగిరీ చార్ట్ లేదా పూర్తి బ్యాకప్.',
    'grocerySpendMonth': 'ఈ నెల గ్రోసరీ ఖర్చు',
    'setBudget': 'బడ్జెట్ సెట్',
    'edit': 'మార్చండి',
    'savedBills': 'సేవ్ చేసిన బిల్లులు',
    'possibleSaving': 'సాధ్యమైన ఆదా',
    'spendingAlerts': 'ఖర్చు అలర్ట్స్',
    'spendingTrend': 'ఖర్చు ట్రెండ్',
    'categorySpend': 'కేటగిరీ ఖర్చు',
    'thisMonth': 'ఈ నెల',
    'allSavedBills': 'అన్ని సేవ్ బిల్లులు',
    'storeComparison': 'స్టోర్ పోలిక',
    'topExpensiveProducts': 'అత్యధిక ఖర్చు వస్తువులు',
    'priceChanges': 'ధర మార్పులు',
    'priceDrops': 'ధర తగ్గుదల',
    'betterPricesNearby': 'దగ్గరలో మంచి ధరలు',
    'buyAgainSoon': 'త్వరలో మళ్లీ కొనండి',
    'scanAnotherMonth':
        'కేటగిరీ పెరుగుదల అలర్ట్స్ చూడడానికి మరొక నెల బిల్లులు స్కాన్ చేయండి.',
    'saveBillsTrend': 'ఖర్చు ట్రెండ్స్ చూడడానికి బిల్లులు సేవ్ చేయండి.',
    'categoriesAppear': 'బిల్ సేవ్ చేసిన తర్వాత కేటగిరీలు కనిపిస్తాయి.',
    'storeSpendAppears':
        'బిల్లులు సేవ్ చేసిన తర్వాత స్టోర్ ఖర్చు కనిపిస్తుంది.',
    'productRankingAppears':
        'స్కాన్‌ల తర్వాత వస్తువుల ఖర్చు ర్యాంకింగ్ కనిపిస్తుంది.',
    'noPriceRises': 'ఇంకా పునరావృత వస్తువుల ధర పెరుగుదల కనిపించలేదు.',
    'priceDropsAppear':
        'పునరావృత వస్తువులు చవకైనప్పుడు ధర తగ్గుదల కనిపిస్తుంది.',
    'scanMoreStores':
        'ధరలు పోల్చడానికి ఒకటి కంటే ఎక్కువ స్టోర్‌ల బిల్లులు స్కాన్ చేయండి.',
    'repeatedProductsAppear':
        'CartSense మళ్లీ కొనాల్సి ఉంటుందని అంచనా వేసినప్పుడు వస్తువులు ఇక్కడ కనిపిస్తాయి.',
  },
};
